{
 "title": "ADAvault Infrastructure Dashboard",
 "description": "Stake Pool Performance Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "CPU Utilisation (% per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100-(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "cpu{{cpu}}-{{instance}}"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU {{instance}}"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Mem {{instance}}"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "Swap {{instance}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk {{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Available Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Time Synchronization",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. {{instance}}"
    },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. {{instance}}" }
   ]
  },
  {
   "title": "Disk Write (bytes/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "File Descriptors Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Network packets transmitted (rate per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total[1m])"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer (1 hr Rolling Window)",
   "type": "timeseries",
   "description": "Inbound and outbound data transfer across the secondary cluster",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Network Packets Received (rate per min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total[1m])"
    }
   ]
  }
 ]
}