{
 "title": "cnHids Summary Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "OSSEC Alert 5m Rate",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\",type=~\"^alerts{0,}$\"}[5m])) by (level)",
     "legendFormat": "Level {{ level }}"
    }
   ]
  },
  {
   "title": "Active Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "ossec_metrics_active_agents" }
   ]
  },
  {
   "title": "Total Agents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "ossec_metrics_total_agents" }
   ]
  },
  {
   "title": "Alerts by Application",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\",application!=\"\"}[$__range])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Alert Classification",
   "type": "text",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 8 },
   "options": {
    "content": "\n00 - Ignored - No action taken. Used to avoid false positives. These rules are scanned before all the others. They include events with no security relevance.\n\n01 - None\n\n02 - System low priority notification - System notification or status messages. They have no security relevance.\n\n03 - Successful/Authorized events - They include successful login attempts, firewall allow events, etc.\n\n04 - System low priority error - Errors related to bad configurations or unused devices/applications. They gemerally have no security relevance and are usually caused by default installations or software testing.\n\n05 - User generated error - They include missed passwords, denied actions, etc. By themselves they have no security relevance.\n\n06 - Low relevance attack - for example a virus that has no affect on the system (like code red for apache servers, etc). They also frequently include IDS events and errors.\n\n07 - “Bad word” matching. They include words like “bad”, “error”, etc. These events are mostly unclassified and may have some security relevance.\n\n08 - First time seen - for example the first time an IDS event is fired or the first time a user logs in. If you just started using OSSEC HIDS these messages will probably be frequent. After a while they should go away, It also includes security relevant actions (like the starting of a sniffer such as tcpdump).\n\n09 - Error from invalid source - Include attempts to login as an unknown user or from an invalid source. May have security relevance (specially if repeated). They also include errors regarding the root account.\n\n10 - Multiple user generated errors - They include multiple bad passwords, multiple failed logins, etc. and may indicate an attack a user just forgot his credentials.\n\n11 - Integrity checking warning - They include messages regarding the modification of binaries or the presence of rootkits (by rootcheck). If you just modified your system configuration you should be fine regarding the “syscheck” messages. They may indicate a successful attack. Also includes IDS events that will be ignored (high number of repetitions).\n\n12 - High importance event - They include error or warning messages from the system, kernel, etc. They may indicate an attack against a specific application.\n\n13 - Unusual error (high importance) - most times this is a match against a common attack pattern.\n\n14 - High importance security event. Most times triggered due to correlation and it indicates an attack.\n\n15 - Severe attack - No chances of false positives. Immediate attention is necessary.\n\n\n\n\n"
   }
  },
  {
   "title": "Alerts By Level",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\"}[$__range])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Alerts by Host",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\"}[$__range])) by (host)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "title": "Alerts by Source User",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\",srcuser!=\"\"}[$__range])) by (srcuser)",
     "legendFormat": "{{srcuser}}"
    }
   ]
  },
  {
   "title": "Alerts by Destination User",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(promtail_custom_ossec_alerts_total{job=\"ossec\",dstuser!=\"\"}[$__range])) by (dstuser)",
     "legendFormat": "{{ level }}"
    }
   ]
  }
 ]
}