{
 "title": "ADAvault Stake Pool",
 "description": "Stake Pool Performance Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Node Uptime (hours)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(time()-cardano_node_metrics_nodeStartTime_int)/3600"
    }
   ]
  },
  {
   "title": "Time Synchronization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Memory {{instance}}"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100",
     "legendFormat": "SWAP {{instance}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk {{instance}}"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int"
    }
   ]
  },
  {
   "title": "About to lead",
   "type": "stat",
   "description": "The number of blocks that the node has seen since starting where it is ready to lead",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blocks Forged (since restart)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation (% per min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)"
    }
   ]
  },
  {
   "title": "Node is leader (since restart)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "KES remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_metrics_blockNum_int[150s]) *60"
    }
   ]
  },
  {
   "title": "Mempool bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int"
    }
   ]
  },
  {
   "title": "Txns Processed per sec (30mins rolling window)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_txsProcessedNum_int [60m])"
    }
   ]
  },
  {
   "title": "Mempool Txns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int"
    }
   ]
  },
  {
   "title": "Total Txns Processed (since restart)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int"
    }
   ]
  },
  {
   "title": "Active Memory (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Node current \"residency\" live data (GB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)"
    }
   ]
  },
  {
   "title": "File Descriptors Allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated" }
   ]
  },
  {
   "title": "Disk Write (bytes/min)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer (1 hr Rolling Window)",
   "type": "graph",
   "description": "Inbound and outbound data transfer across the secondary cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Density",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real"
    }
   ]
  },
  {
   "title": "Slot in epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int"
    }
   ]
  },
  {
   "title": "Network Packets Received (rate per min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_packets_total[1m])"
    }
   ]
  },
  {
   "title": "Network packets transmitted (rate per min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total[1m])"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cardano_node_metrics_epoch_int" }
   ]
  },
  {
   "title": "Slot Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int"
    }
   ]
  }
 ]
}